apiVersion: v1
entries:
  seaweedfs:
  - apiVersion: v1
    appVersion: "3.46"
    created: "2023-04-17T05:01:50.181994233Z"
    description: SeaweedFS
    digest: 8cbdd6e17e9d828e4935280b504672c9888093d686b841c78511cd575d399b7f
    name: seaweedfs
    urls:
    - https://seaweedfs.github.io/seaweedfs/helm/seaweedfs-3.46.tgz
    version: "3.46"
  - apiVersion: v1
    appVersion: "3.45"
    created: "2023-04-03T05:56:34.174881818Z"
    description: SeaweedFS
    digest: 35be7e2949cc4ab3239a333822f26337428091ae2018821579321dbc57552e12
    name: seaweedfs
    urls:
    - https://seaweedfs.github.io/seaweedfs/helm/seaweedfs-3.45.tgz
    version: "3.45"
  - apiVersion: v1
    appVersion: "3.44"
    created: "2023-03-20T03:39:57.830172001Z"
    description: SeaweedFS
    digest: 316dda8acb0a132f254100e08af6c91a37fb6435ebcd625a84cc80268db8b475
    name: seaweedfs
    urls:
    - https://seaweedfs.github.io/seaweedfs/helm/seaweedfs-3.44.tgz
    version: "3.44"
  - apiVersion: v1
    appVersion: "3.43"
    created: "2023-02-21T01:05:06.654751634Z"
    description: SeaweedFS
    digest: b8b9071dd8624a06d47b865a0a0e64d1093c2f0406ede47f40019fe9ea7e82a5
    name: seaweedfs
    urls:
    - https://seaweedfs.github.io/seaweedfs/helm/seaweedfs-3.43.tgz
    version: "3.43"
  - apiVersion: v1
    appVersion: "3.42"
    created: "2023-02-18T05:19:22.925911445Z"
    description: SeaweedFS
    digest: 56e333e6fa215fe441dbf6f6838ee704dde03812c5432787bc4a06673a67c5cf
    name: seaweedfs
    urls:
    - https://seaweedfs.github.io/seaweedfs/helm/seaweedfs-3.42.tgz
    version: "3.42"
generated: "2023-04-17T05:01:50.178470594Z"
